M48
; DRILL file {KiCad 8.0.1} date 2024-06-16T17:47:39-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-16T17:47:39-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0472
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0669
%
G90
G05
T1
X5.797Y-2.637
T2
X6.1776Y-2.6567
T3
X5.581Y-2.6042
X5.581Y-2.7042
T4
X5.331Y-2.699
T5
X5.231Y-2.599
X5.231Y-2.799
X5.431Y-2.599
X5.431Y-2.799
M30
